### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by jinzhongjia** [wzv5/ScoopBucket#1]
我正常使用scoop update来进行更新，然后其他包更新正常，但是到这个bucket后就会报出以下错误
我的环境：
系统：win10企业版
命令行工具：powershell7最新版

```bash
Updating 'wzv5' bucket...
MethodInvocationException: C:\Users\jinzh\scoop\apps\scoop\current\lib\core.ps1:1111
Line |
1111 |          [System.IO.File]::WriteAllLines($FilePath, $InputObject)
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "WriteAllLines" with "2" argument(s): "Access to the path
     | 'C:\Users\jinzh\.config\scoop\config.json' is denied."
```

目前已经尝试过将bucket删除重新添加，但是还会提示该错误
我已经查看过`C:\Users\jinzh\.config\scoop\config.json`配置文件具有写权限

**Comment by wzv5** [comment]
这就不清楚了，可能是scoop的bug？

**Comment by jinzhongjia** [comment]
> 这就不清楚了，可能是scoop的bug？

刚刚查了一下相关资料，可能是scoop的bug

**Comment by jinzhongjia** [comment]
问题解决了，不知道为什么`C:\Users\jinzh\.config\scoop\config.json`这个文件它就是没有权限访问，我明明已经把权限都开了
最后我尝试直接把json配置文件删除后一切正常
